/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.proyectobanco.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author RICARDO
 */
public class MainForm extends javax.swing.JFrame {

  /**
   * Creates new form ProyectoBanco
   */
  public MainForm() {
    initComponents();
    setExtendedState(MAXIMIZED_BOTH);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSeparator2 = new javax.swing.JSeparator();
    desktopPane = new javax.swing.JDesktopPane();
    jToolBar2 = new javax.swing.JToolBar();
    jbuttoncuenta = new javax.swing.JButton();
    jbuttonSimple = new javax.swing.JButton();
    jbuttonCompuesto = new javax.swing.JButton();
    jSeparator3 = new javax.swing.JToolBar.Separator();
    jButtonSalir = new javax.swing.JButton();
    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    jMenuSalir = new javax.swing.JMenuItem();
    menuOpciones = new javax.swing.JMenu();
    menuOpcionesRetiro = new javax.swing.JMenuItem();
    menuOpcionesSimple = new javax.swing.JMenuItem();
    menuOpcionesCompuesto = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(360, 222));

    jToolBar2.setFloatable(false);
    jToolBar2.setRollover(true);

    jbuttoncuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/proyectobanco/images/retiro2.jpg"))); // NOI18N
    jbuttoncuenta.setText("Retiro");
    jbuttoncuenta.setFocusable(false);
    jbuttoncuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jbuttoncuenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jbuttoncuenta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbuttoncuentaActionPerformed(evt);
      }
    });
    jToolBar2.add(jbuttoncuenta);

    jbuttonSimple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/proyectobanco/images/simple2.jpg"))); // NOI18N
    jbuttonSimple.setText(" Simple");
    jbuttonSimple.setFocusable(false);
    jbuttonSimple.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jbuttonSimple.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jbuttonSimple.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbuttonSimpleActionPerformed(evt);
      }
    });
    jToolBar2.add(jbuttonSimple);

    jbuttonCompuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/proyectobanco/images/compuesto2.jpg"))); // NOI18N
    jbuttonCompuesto.setText("Compuesto");
    jbuttonCompuesto.setFocusable(false);
    jbuttonCompuesto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jbuttonCompuesto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jbuttonCompuesto.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbuttonCompuestoActionPerformed(evt);
      }
    });
    jToolBar2.add(jbuttonCompuesto);
    jToolBar2.add(jSeparator3);

    jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/proyectobanco/images/salir2.jpg"))); // NOI18N
    jButtonSalir.setText("Salir");
    jButtonSalir.setFocusable(false);
    jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonSalirActionPerformed(evt);
      }
    });
    jToolBar2.add(jButtonSalir);

    fileMenu.setMnemonic('f');
    fileMenu.setText("File");
    fileMenu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fileMenuActionPerformed(evt);
      }
    });

    jMenuSalir.setText("Salir");
    jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuSalirActionPerformed(evt);
      }
    });
    fileMenu.add(jMenuSalir);

    menuBar.add(fileMenu);

    menuOpciones.setText("Opciones");

    menuOpcionesRetiro.setText("Retiro");
    menuOpcionesRetiro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuOpcionesRetiroActionPerformed(evt);
      }
    });
    menuOpciones.add(menuOpcionesRetiro);

    menuOpcionesSimple.setText("Interes Simple");
    menuOpcionesSimple.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuOpcionesSimpleActionPerformed(evt);
      }
    });
    menuOpciones.add(menuOpcionesSimple);

    menuOpcionesCompuesto.setText("Interes Compuesto");
    menuOpcionesCompuesto.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuOpcionesCompuestoActionPerformed(evt);
      }
    });
    menuOpciones.add(menuOpcionesCompuesto);

    menuBar.add(menuOpciones);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuOpcionesRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesRetiroActionPerformed
    // TODO add your handling code here:
/*
JInternalFrame view = new CuentaView();
desktopPane.add(view);
view.setVisible(true);*/

cargarFormulario(CuentaView.class);

  }//GEN-LAST:event_menuOpcionesRetiroActionPerformed

  private void menuOpcionesSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesSimpleActionPerformed
    // TODO add your handling code here:
 cargarFormulario(SimpleView.class);

  }//GEN-LAST:event_menuOpcionesSimpleActionPerformed

  private void menuOpcionesCompuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesCompuestoActionPerformed
    // TODO add your handling code here:
 cargarFormulario(CompuestoView.class);
  }//GEN-LAST:event_menuOpcionesCompuestoActionPerformed

  private void jbuttonSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSimpleActionPerformed
    // TODO add your handling code here:
    cargarFormulario(SimpleView.class);
  }//GEN-LAST:event_jbuttonSimpleActionPerformed

  private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
    // TODO add your handling code here:
   
  }//GEN-LAST:event_fileMenuActionPerformed

  private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
    // TODO add your handling code here:
        System.exit(0);
  }//GEN-LAST:event_jMenuSalirActionPerformed

  private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_jButtonSalirActionPerformed

  private void jbuttoncuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttoncuentaActionPerformed
    // TODO add your handling code here:
    cargarFormulario(CuentaView.class);
  }//GEN-LAST:event_jbuttoncuentaActionPerformed

  private void jbuttonCompuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCompuestoActionPerformed
    // TODO add your handling code here:
    cargarFormulario(CompuestoView.class);
  }//GEN-LAST:event_jbuttonCompuestoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JButton jButtonSalir;
  private javax.swing.JMenuItem jMenuSalir;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JToolBar.Separator jSeparator3;
  private javax.swing.JToolBar jToolBar2;
  private javax.swing.JButton jbuttonCompuesto;
  private javax.swing.JButton jbuttonSimple;
  private javax.swing.JButton jbuttoncuenta;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuOpciones;
  private javax.swing.JMenuItem menuOpcionesCompuesto;
  private javax.swing.JMenuItem menuOpcionesRetiro;
  private javax.swing.JMenuItem menuOpcionesSimple;
  // End of variables declaration//GEN-END:variables

  private void cargarFormulario(Class<?> aClass) {
    try {
     // Variable de control
     JInternalFrame view = null;
     // Buscar objeto
     for(JInternalFrame form: desktopPane.getAllFrames()){
       if(aClass.isInstance(form)){
         view = form;
         break;
       }
     }
     // Si no lo encuentra...
     if(view == null){
       view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
       desktopPane.add(view);
     }
     // Hacer visible el formulario
     view.setVisible(true);
     view.setSelected(true);
    } catch (Exception e) {
    }
  }

}
