/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.app.view;

import pe.egcc.app.controller.AppController;

/**
 *
 * @author S61851
 */
public class FibonacciForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form FibonacciForm
     */
    public FibonacciForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumero = new javax.swing.JTextField();
        txtProcesar = new javax.swing.JButton();
        lblRespuesta = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Fibonacci");

        txtNumero.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });

        txtProcesar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtProcesar.setText("Procesar");
        txtProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcesarActionPerformed(evt);
            }
        });

        lblRespuesta.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRespuesta.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121))
                    .addComponent(lblRespuesta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcesarActionPerformed
        int n;
        n=Integer.parseInt(txtNumero.getText());
        AppController control = new AppController();
        lblRespuesta.setText(control.fibonacci(n));
    }//GEN-LAST:event_txtProcesarActionPerformed

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        char car = evt.getKeyChar();
            // Verificar si la tecla pulsada no es un digito
            if(((car < '0') ||
               (car > '9')) &&
               (car != '\b' /*corresponde a BACK_SPACE*/))
            {
               evt.consume();  // ignorar el evento de teclado
            }
    }//GEN-LAST:event_txtNumeroKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JButton txtProcesar;
    // End of variables declaration//GEN-END:variables
}
