/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.app.view;

import pe.egcc.app.controller.AppController;

/**
 *
 * @author S61851
 */
public class McdMcmForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form McdMcmForm
     */
    public McdMcmForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumero1 = new javax.swing.JTextField();
        txtProcesar = new javax.swing.JButton();
        lblRespuesta = new javax.swing.JLabel();
        txtNumero2 = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("MCD & MCM");

        txtNumero1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumero1KeyTyped(evt);
            }
        });

        txtProcesar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtProcesar.setText("Procesar");
        txtProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcesarActionPerformed(evt);
            }
        });

        lblRespuesta.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRespuesta.setBorder(new javax.swing.border.MatteBorder(null));

        txtNumero2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtNumero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumero2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcesarActionPerformed
        int numero1, numero2;
        int mcm, mcd;
        String reporte;

        numero1=Integer.parseInt(txtNumero1.getText());
        numero2=Integer.parseInt(txtNumero2.getText());
        AppController control = new AppController();
        mcd=control.mcd(numero1,numero2);
        mcm=control.mcm(numero1,numero2);
        reporte="El MCD/MCM es " + mcd + "/" + mcm;
        lblRespuesta.setText(reporte);

    }//GEN-LAST:event_txtProcesarActionPerformed

    private void txtNumero2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero2KeyTyped
        char car = evt.getKeyChar();
            // Verificar si la tecla pulsada no es un digito
            if(((car < '0') ||
               (car > '9')) &&
               (car != '\b' /*corresponde a BACK_SPACE*/))
            {
               evt.consume();  // ignorar el evento de teclado
            }
    }//GEN-LAST:event_txtNumero2KeyTyped

    private void txtNumero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero1KeyTyped
        char car = evt.getKeyChar();
            // Verificar si la tecla pulsada no es un digito
            if(((car < '0') ||
               (car > '9')) &&
               (car != '\b' /*corresponde a BACK_SPACE*/))
            {
               evt.consume();  // ignorar el evento de teclado
            }
    }//GEN-LAST:event_txtNumero1KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JButton txtProcesar;
    // End of variables declaration//GEN-END:variables
}
