/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.view;

import javax.swing.JOptionPane;
import pe.egcc.app.lib.PromedioService;

/**
 *
 * @author B202-09
 */
public class PromedioView extends javax.swing.JFrame {

 /**
  * Creates new form PromedioView
  */
 public PromedioView() {
  initComponents();
 }

 /**
  * This method is called from within the constructor to
  * initialize the form. WARNING: Do NOT modify this code.
  * The content of this method is always regenerated by the
  * Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  btnPromedio1 = new javax.swing.JButton();
  btnPromedio2 = new javax.swing.JButton();
  jLabel1 = new javax.swing.JLabel();
  btnPromedio3 = new javax.swing.JButton();
  btnPromedio4 = new javax.swing.JButton();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

  btnPromedio1.setText("Promedio de 2 numeros");
  btnPromedio1.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnPromedio1ActionPerformed(evt);
   }
  });

  btnPromedio2.setText("Promedio de 3 numeros");
  btnPromedio2.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnPromedio2ActionPerformed(evt);
   }
  });

  jLabel1.setText("Seleccione la operacion que desea realizar:");

  btnPromedio3.setText("Promedio de 4 numeros");
  btnPromedio3.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnPromedio3ActionPerformed(evt);
   }
  });

  btnPromedio4.setText("Promedio de 5 numeros");
  btnPromedio4.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnPromedio4ActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(layout.createSequentialGroup()
      .addGap(118, 118, 118)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(btnPromedio2)
       .addComponent(btnPromedio1)
       .addComponent(btnPromedio3)
       .addComponent(btnPromedio4)))
     .addGroup(layout.createSequentialGroup()
      .addGap(77, 77, 77)
      .addComponent(jLabel1)))
    .addContainerGap(73, Short.MAX_VALUE))
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(32, 32, 32)
    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(18, 18, 18)
    .addComponent(btnPromedio1)
    .addGap(18, 18, 18)
    .addComponent(btnPromedio2)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(btnPromedio3)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(btnPromedio4)
    .addContainerGap(90, Short.MAX_VALUE))
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void btnPromedio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedio1ActionPerformed
  // TODO add your handling code here:
  PromedioService serv = new PromedioService();
  double n1, n2;
  String num1 = JOptionPane.showInputDialog("Ingrese numero:");
  n1 = Double.parseDouble(num1);
  String num2 = JOptionPane.showInputDialog("Ingrese numero:");
  n2 = Double.parseDouble(num2);

  JOptionPane.showMessageDialog(null, "El promedio es: " + serv.promedio(n1, n2), "PROMEDIO", JOptionPane.PLAIN_MESSAGE);
 }//GEN-LAST:event_btnPromedio1ActionPerformed

 private void btnPromedio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedio2ActionPerformed
  // TODO add your handling code here:

  PromedioService serv = new PromedioService();
  double n1, n2, n3;
  String num1 = JOptionPane.showInputDialog("Ingrese numero:");
  n1 = Double.parseDouble(num1);
  String num2 = JOptionPane.showInputDialog("Ingrese numero:");
  n2 = Double.parseDouble(num2);
  String num3 = JOptionPane.showInputDialog("Ingrese numero:");
  n3 = Double.parseDouble(num3);

  JOptionPane.showMessageDialog(null, "El promedio es: " + serv.promedio(n1, n2, n3), "PROMEDIO", JOptionPane.PLAIN_MESSAGE);


 }//GEN-LAST:event_btnPromedio2ActionPerformed

 private void btnPromedio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedio3ActionPerformed
  // TODO add your handling code here:
  PromedioService serv = new PromedioService();

  String num1 = JOptionPane.showInputDialog("Ingrese numero:");
  double n1 = Double.parseDouble(num1);
  String num2 = JOptionPane.showInputDialog("Ingrese numero:");
  double n2 = Double.parseDouble(num2);
  String num3 = JOptionPane.showInputDialog("Ingrese numero:");
  double n3 = Double.parseDouble(num3);
  String num4 = JOptionPane.showInputDialog("Ingrese numero:");
  double n4 = Double.parseDouble(num4);
  JOptionPane.showMessageDialog(null, "El promedio es: " + serv.promedio(n1, n2, n3, n4), "PROMEDIO", JOptionPane.PLAIN_MESSAGE);

 }//GEN-LAST:event_btnPromedio3ActionPerformed

 private void btnPromedio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedio4ActionPerformed
  // TODO add your handling code here:
  PromedioService serv = new PromedioService();

  String num1 = JOptionPane.showInputDialog("Ingrese numero:");
  double n1 = Double.parseDouble(num1);
  String num2 = JOptionPane.showInputDialog("Ingrese numero:");
  double n2 = Double.parseDouble(num2);
  String num3 = JOptionPane.showInputDialog("Ingrese numero:");
  double n3 = Double.parseDouble(num3);
  String num4 = JOptionPane.showInputDialog("Ingrese numero:");
  double n4 = Double.parseDouble(num4);
  String num5 = JOptionPane.showInputDialog("Ingrese numero:");
  double n5 = Double.parseDouble(num5);
  JOptionPane.showMessageDialog(null, "El promedio es: " + serv.promedio(n1, n2, n3, n4, n5), "PROMEDIO", JOptionPane.PLAIN_MESSAGE);


 }//GEN-LAST:event_btnPromedio4ActionPerformed

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(PromedioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(PromedioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(PromedioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(PromedioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new PromedioView().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton btnPromedio1;
 private javax.swing.JButton btnPromedio2;
 private javax.swing.JButton btnPromedio3;
 private javax.swing.JButton btnPromedio4;
 private javax.swing.JLabel jLabel1;
 // End of variables declaration//GEN-END:variables
}
